[package]
name = "tree-sitter-c-proc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-c = "0.20.7"
quote = "1.0.36"
syn = "2.0.58"

[lib]
proc-macro = true
